### PR TITLE
Ranged_names from Office Open XML functionality added

### PR DESCRIPTION
**Pull request by BenoitDalFerro**
Ranged_names from Office Open XML functionality added as self.rangednames_openpyxl of an ExcelComWrapper instance. Overcomes win32.com's inability to handle ranged names with single line/column.

Shuffled self.rangednames with win32.com method to get_rangednames function.

Added try/except to modules import & openpyxl ranged names acquisition to prevent crash.

### CODE REVIEW

**Comment by dgorissen** [comment]
Quick notes:

- make sure all dependencies are listed in setup.py. Then there should be no need to try catch imports. The only exception perhaps being to help portability (eg, win32 wont work on linux)

- why do you need to blocks of code doing essentially the same thing (getting named ranges). If the openpyxl version is the more robust and correct one, use only that and remove the other.
Should also be no need for two instance variables to hold the rangednames.

- more fundamentally it feels a bit wrong to have two access mechanisms (com & openxml) in the same implementation. Ideally all the com stuff could be dropped but I recall that is rather non trivial. So leave both if you need to but keep it clean. Perhaps also then rename the class from ExcelComWrapper to ExcelWrapper.

**Comment by BenCEEME** [comment]
Much appreciated input, will do.

On last point very much agree.
Since ExcelComWrapper has convenient name suggest to build ExcelOpenpyexcelWrapper class in addition to ExcelComWrapper class based on win32. Initially a clone of its win32 parent, it would see its inner workings progressively replaced by openpyxl commands.

Suggest to continue my fork's own way until I have something more substantial to show prior to consider another update of your Pycel's master.

**Comment by dgorissen** [comment]
Sounds good.

**Comment by BenCEEME** [comment]
Rangednames now fully supported in my fork.

Benefits to Pycel master overcome in my opinion the lack of consistency (win32 & openpyxl coexisting, not yet separated in two clearly defined classes).

TODO: code to match Rangedname with Rangedname formula in def Cell() not very elegant/pythonic, eventually sub-optimal.

**Comment by BenCEEME** [comment]
Btw clean up on exception handling for dependent packages (numpy, openpyxl) now documented in setup.py

Co-existence of rangednames_openpyxl & get_rangednames() will remain until clean ExcelOpenpyxlWrapper class can be written down (may take a while) owing to discrepancy between the two (and eventual unforseen benefits of win32 method, time will tell).

**Comment by stephenrauch** [comment]
Thanks for submitting this PR.  But at this point I believe it has been OBE (Overcome By Events). I am going to close the PR since _ranged_names_ functionality has been covered by: https://github.com/dgorissen/pycel/pull/37

**Pull request closed without merging**
