### PR TITLE
Defined Names acquisition

### PR DESCRIPTION
**Pull request by BenCEEME**
get_rangednames function, returns numpy array containing for each defined name its VBA id, name and formula. numpy array has fields properly defined as 'id', 'formula' and 'names'.

WARNING: by default numpy array requires dtype declaration to specify character length (here 'S200', i.e. 200 characters)
TODO: automate detection of max string length to set up numpy array accordingly
TODO: discriminate between worksheet & workbook ranged names

### CODE REVIEW

**Comment by dgorissen** [comment]
No reason to store the result in the object instance? (ie, on self)

**Comment by BenCEEME** [comment]
Got there when I tried to pass the array to the other modules. Update tomorrow.


De : Dirk Gorissen [mailto:notifications@github.com]
Envoyé : Monday, September 14, 2015 09:19 PM
À : dgorissen/pycel <pycel@noreply.github.com>
Cc : Dal Ferro Benoit (ENGIE)
Objet : Re: [pycel] Defined Names acquisition (#13)


No reason to store the result in the object instance? (ie, on self)

—
Reply to this email directly or view it on GitHub<https://github.com/dgorissen/pycel/pull/13#issuecomment-140181436>.


GDF SUEZ Mail Disclaimer: http://www.gdfsuez.com/disclaimer/disclaimer-fr.html

**Comment by BenCEEME** [comment]
Code updated.
Shuffled ranged names acquisition from get_rangednames(self) function to object instance

**Comment by zalazhar** [comment]
This breaks the example code, bringing this to the init means that app has to exist. And it is not yet . I get the following error: <pre> self.rangednames = np.zeros(shape = (int(self.app.ActiveWorkbook.Names.Count),1), dtype=[('id', 'int_'), ('name', 'S200'), ('formula', 'S200')])
AttributeError: 'NoneType' object has no attribute 'ActiveWorkbook'
Exception in thread Thread-1 (most likely raised during interpreter shutdown): </pre>. Commenting lets the example code work.

**Pull request merged**
