### PR TITLE
Handle worksheet formulas with circular references

### LINKED ISSUE #56: Support for iterative calculation
Microsoft Excel currently includes functionality to perform [iterative calculations](https://support.office.com/en-us/article/change-formula-recalculation-iteration-or-precision-73fc7dac-91cf-4d36-86e8-67124f6bcce4) when formulas contain circular references. By default further processing of circular formulas is broken after 100 iterations or once the value of the target cell changes by less than 0.01.

Current evaluation of pycel on formula with circular references does not take number of iterations or minimum value change into account during its execution. The result is an infinite cyclical execution that only breaks once the maximum recursion depth is reached.

Would there be any way to add this functionality or otherwise provide direction to proper execution state locations so that this functionality can be added via PR?

Thanks for the incredible library!

### PR DESCRIPTION
**Pull request by GeoJosh**
Added safeguards to prevent recursion-based crashes for worksheets that contain circular references. A workbook has been included that exhibits this behavior and proper calculations are detected. Unpublished tests also pass for internal documents.

 - [x] closes #56
 - [x] tests added / passed
 - [x] passes ``tox``

### CODE REVIEW

**Comment by stephenrauch** [comment]
Thanks for taking the time to make this PR.   I will do a more detailed review later, but for now I would suggest this functionality should try not to put much overhead in the more "normal" paths.  If my inspection so far is correct, this code visits all cells in the map even if evaluating only one cell.  This seems expensive.

**Comment by GeoJosh** [comment]
The intention of the PR is to only iterate an internal counter for each relevant cell in a function's execution path [during its evaluation phase](https://github.com/dgorissen/pycel/pull/57/files#diff-e69171b2a3fae044ff0f8f4577d533a2R713). The only time all the cells are touched is [before the evaluation](https://github.com/dgorissen/pycel/pull/57/files#diff-e69171b2a3fae044ff0f8f4577d533a2R758) to ensure that all of the internal counters have been reset. While pre-evaluation of the network graph may provide some insight into more efficiently handling formulas with circular references I think the method for generating code would need to drastically altered to account for an iterative calculation methodology vs the current traverse-first code generated.

Unlike Excel's evaluation code the generated lambda code for the functions results in a traverse-first execution path before the cells are evaluated (vs eval-first traversal) and some testing had to be done to figure out how Excel initialized the values once the iteration limit is reached. This may result is a mismatch for more complicated nested functionality, but I don't have an example of that at this time.

Thank you for your review and any suggestions for further modification or implementation.

**Comment by stephenrauch** [comment]
I realize all of the cells are only visited before the evaluation, but they are all visited.  I have sheets with 10,000's of cells.  To visit all cells, to evaluate one cell, seems less than optimum.  So, if we are going to put in extra work to deal with graph cycles, I think the work should be either be during the compile, or when explicitly evaluating cycles.

**Comment by stephenrauch** [comment]
Thanks again for this submission.  I have merged it, but I merged another change right after it which implements a more complete solution and lowers the overhead for the non-circular case. The change in #58 has a different API than one I merged here. Except for the API change it should be a super-set of the change here.

**Pull request merged**
